import type { Edge, Node } from '@xyflow/svelte';

// Default nodes are a simple graph to create cables

export const initialNodes: Node[] = [
    {
        id: 'Desc_OreCopper_C_gtdmbu3w0w',
        type: 'custom',
        position: { x: 259.98179064828753, y: 91.1375310408956 },
        data: { recipeName: 'Desc_OreCopper_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
    {
        id: 'Recipe_IngotCopper_C_42452rfun4',
        type: 'custom',
        position: { x: 561.3166405204688, y: 95.60228934195946 },
        data: { recipeName: 'Recipe_IngotCopper_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
    {
        id: 'Recipe_Alternate_FusedWire_C_ytrb51kteu',
        type: 'custom',
        position: { x: 905.3960032091554, y: 104.87388893536718 },
        data: { recipeName: 'Recipe_Alternate_FusedWire_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
    {
        id: 'Recipe_IngotCaterium_C_ins2o477ut',
        type: 'custom',
        position: { x: 570.829342383139, y: 337.13413886291875 },
        data: { recipeName: 'Recipe_IngotCaterium_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
    {
        id: 'Desc_OreGold_C_a2s5hm7pq5',
        type: 'custom',
        position: { x: 250.1511466469803, y: 338.3306992947701 },
        data: { recipeName: 'Desc_OreGold_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
    {
        id: 'Recipe_Cable_C_neyumuce38',
        type: 'custom',
        position: { x: 1200.220129536943, y: 101.41173378820505 },
        data: { recipeName: 'Recipe_Cable_C' },
        origin: [0.5, 0.5],
        measured: { width: 200, height: 170 },
        selected: false,
        dragging: false,
    },
];

export const initialEdges: Edge[] = [
    {
        id: 'Desc_OreCopper_C_gtdmbu3w0wDesc_OreCopper_C-Recipe_IngotCopper_C_42452rfun4Desc_OreCopper_C-',
        source: 'Desc_OreCopper_C_gtdmbu3w0w',
        target: 'Recipe_IngotCopper_C_42452rfun4',
        sourceHandle: 'Desc_OreCopper_C',
        targetHandle: 'Desc_OreCopper_C',
        selected: false,
    },
    {
        id: 'Recipe_IngotCopper_C_42452rfun4Desc_CopperIngot_C-Recipe_Alternate_FusedWire_C_ytrb51kteuDesc_CopperIngot_C-',
        source: 'Recipe_IngotCopper_C_42452rfun4',
        target: 'Recipe_Alternate_FusedWire_C_ytrb51kteu',
        sourceHandle: 'Desc_CopperIngot_C',
        targetHandle: 'Desc_CopperIngot_C',
        selected: false,
    },
    {
        id: 'Recipe_Alternate_FusedWire_C_ytrb51kteuDesc_GoldIngot_C-Recipe_IngotCaterium_C_ins2o477utDesc_GoldIngot_C-',
        source: 'Recipe_IngotCaterium_C_ins2o477ut',
        target: 'Recipe_Alternate_FusedWire_C_ytrb51kteu',
        sourceHandle: 'Desc_GoldIngot_C',
        targetHandle: 'Desc_GoldIngot_C',
        selected: false,
    },
    {
        id: 'Recipe_IngotCaterium_C_ins2o477utDesc_OreGold_C-Desc_OreGold_C_a2s5hm7pq5Desc_OreGold_C-',
        source: 'Desc_OreGold_C_a2s5hm7pq5',
        target: 'Recipe_IngotCaterium_C_ins2o477ut',
        sourceHandle: 'Desc_OreGold_C',
        targetHandle: 'Desc_OreGold_C',
        selected: false,
    },
    {
        id: 'Recipe_Alternate_FusedWire_C_ytrb51kteuDesc_Wire_C-Recipe_Cable_C_neyumuce38Desc_Wire_C-',
        source: 'Recipe_Alternate_FusedWire_C_ytrb51kteu',
        target: 'Recipe_Cable_C_neyumuce38',
        sourceHandle: 'Desc_Wire_C',
        targetHandle: 'Desc_Wire_C',
        selected: false,
    },
];